services:
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "7070:8080"
      - "50000:50000"
    user: root
    volumes:
      - ./volumes/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/hsjack/Documents/Github/boostcamp/backendProject:/var/jenkins_home/workspace/backend5_Test_local/backendProject  # 프로젝트 연결
    # 개발자가 직접 멈추지 않으면 일단 스탑되지 않음
    restart: unless-stopped